upstream_project_url: https://github.com/davisking/dlib
upstream_tag_template: v{version}
copy_upstream_release_description: false
 
jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

